=== ahmedEH/bibleotheque/xml/bibleotheque.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Wed Apr 15 14:14:07 CEST 2020 -->


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">   
            

<!-- Les simple types crÃ©e -->
<xs:simpleType name="annee">
<xs:restriction base="xs:integer">
	<xs:maxInclusive value="2020"/>
	<xs:minInclusive value="0"/>
</xs:restriction>
</xs:simpleType>
<!-- XML Shema -->
<xs:element name="bibleotheque">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="livre" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="titre" type="xs:string"/>
						<xs:element name="annee_prod" type="annee"/>
						<xs:element name="isbn" type="xs:string"/>
						<xs:element name="auteur" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="nom" type="xs:string"/>
									<xs:element name="prenom" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="section" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="titre" type="xs:string"/>
									<xs:element name="chapitre" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="titre" type="xs:string"/>
												<xs:element name="paragraphe" maxOccurs="unbounded" type="xs:string"/>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== ahmedEH/bibleotheque/xml/bibleotheque.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bibleotheque.xsl"?>
<bibleotheque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bibleotheque.xsd">
	<livre>
		<titre>Amour impossible</titre>
		<annee_prod>2020</annee_prod>
		<isbn>00A001</isbn>
		<auteur>
			<nom>Ahmed mahmoud</nom>
			<prenom>Ebou Elhassani</prenom>
		</auteur>
		<section>
			<titre>Les causes</titre>
			<chapitre>
				<titre>Le premier amour</titre>
				<paragraphe>
					Le premier amour n’est pas vraiment le premier
La façon dont nous créons des liens avec une autre personne pour la première fois est forcément liée à nos relations antérieures avec nos proches et notre famille. Depuis tout petit, nous établissons des liens plus ou moins intimes avec d’autres personnes. Nous apprenons à partager, à mener, à collaborer, à jouer, à aimer mais aussi à gérer nos premières déceptions.

Les relations que nous avons créées avec nos parents et nos proches en général influent aussi sur notre façon de tisser des liens avec de nouvelles personnes. Nous sommes plus ou moins dépendants, sûrs de nous-mêmes, méfiants, agressifs… Ces relations débutées depuis l’enfance vont nous forger pour le futur.

Voilà pourquoi on peut dire qu’il y a d’autres "amours" avant le premier amour. Ces amours et amitiés, bien qu’elles ne soient pas charnelles, nous apprennent et nous marquent pour toujours.
				</paragraphe>
				<paragraphe>
					Contrairement aux précédentes relations (amicales et familiales), le premier amour fait naître chez nous de nombreuses attentes. Ces dernières sont le plus souvent liées à ce que nous avons vu à la télévision, au cinéma, à ce qu’on nous a raconté, à ce qu’on a vu à la maison… Les expériences amoureuses de nos proches jouent également sur nos attentes. Ainsi, nous faisons des généralités sur le premier amour. Nous voulons décider de comment nous allons aimer, comment nous allons agir dans la relation, ce que nous recherchons dans le couple et ce que nous voulons éviter. Les plus romantiques peuvent même passer des heures à imaginer comment sera leur premier amour.

Mais quand le premier amour frappe, toutes ces attentes s’effondrent. Nous sommes aveuglés par les émotions et pouvons faire des choses que nous trouvions niaises auparavant. A l’inverse, nous pouvons aussi être déçus par la tournure que prend la relation, ne correspondant pas à nos attentes.

S’adapter à la réalité après le choc suscité par la déception peut être une étape difficile. Mais il faut en tirer des enseignements pour les relations à venir. Même si le premier mauvais réflexe est de comparer nos autres conjoints au premier amour.
				</paragraphe>
			</chapitre>
			<chapitre>
				<titre>Le premier amour</titre>
				<paragraphe>
					Le premier amour n’est pas vraiment le premier
La façon dont nous créons des liens avec une autre personne pour la première fois est forcément liée à nos relations antérieures avec nos proches et notre famille. Depuis tout petit, nous établissons des liens plus ou moins intimes avec d’autres personnes. Nous apprenons à partager, à mener, à collaborer, à jouer, à aimer mais aussi à gérer nos premières déceptions.

Les relations que nous avons créées avec nos parents et nos proches en général influent aussi sur notre façon de tisser des liens avec de nouvelles personnes. Nous sommes plus ou moins dépendants, sûrs de nous-mêmes, méfiants, agressifs… Ces relations débutées depuis l’enfance vont nous forger pour le futur.

Voilà pourquoi on peut dire qu’il y a d’autres "amours" avant le premier amour. Ces amours et amitiés, bien qu’elles ne soient pas charnelles, nous apprennent et nous marquent pour toujours.
				</paragraphe>
				<paragraphe>
					Contrairement aux précédentes relations (amicales et familiales), le premier amour fait naître chez nous de nombreuses attentes. Ces dernières sont le plus souvent liées à ce que nous avons vu à la télévision, au cinéma, à ce qu’on nous a raconté, à ce qu’on a vu à la maison… Les expériences amoureuses de nos proches jouent également sur nos attentes. Ainsi, nous faisons des généralités sur le premier amour. Nous voulons décider de comment nous allons aimer, comment nous allons agir dans la relation, ce que nous recherchons dans le couple et ce que nous voulons éviter. Les plus romantiques peuvent même passer des heures à imaginer comment sera leur premier amour.

Mais quand le premier amour frappe, toutes ces attentes s’effondrent. Nous sommes aveuglés par les émotions et pouvons faire des choses que nous trouvions niaises auparavant. A l’inverse, nous pouvons aussi être déçus par la tournure que prend la relation, ne correspondant pas à nos attentes.

S’adapter à la réalité après le choc suscité par la déception peut être une étape difficile. Mais il faut en tirer des enseignements pour les relations à venir. Même si le premier mauvais réflexe est de comparer nos autres conjoints au premier amour.
				</paragraphe>
			</chapitre>
		</section>
	</livre>

	<livre>
		<titre>Amour impossible</titre>
		<annee_prod>2020</annee_prod>
		<isbn>00A002</isbn>
		<auteur>
			<nom>Ahmed mahmoud</nom>
			<prenom>Ebou Elhassani</prenom>
		</auteur>
		<section>
			<titre>Les causes</titre>
			<chapitre>
				<titre>Le premier amour</titre>
				<paragraphe>
					Le premier amour n’est pas vraiment le premier
La façon dont nous créons des liens avec une autre personne pour la première fois est forcément liée à nos relations antérieures avec nos proches et notre famille. Depuis tout petit, nous établissons des liens plus ou moins intimes avec d’autres personnes. Nous apprenons à partager, à mener, à collaborer, à jouer, à aimer mais aussi à gérer nos premières déceptions.

Les relations que nous avons créées avec nos parents et nos proches en général influent aussi sur notre façon de tisser des liens avec de nouvelles personnes. Nous sommes plus ou moins dépendants, sûrs de nous-mêmes, méfiants, agressifs… Ces relations débutées depuis l’enfance vont nous forger pour le futur.

Voilà pourquoi on peut dire qu’il y a d’autres "amours" avant le premier amour. Ces amours et amitiés, bien qu’elles ne soient pas charnelles, nous apprennent et nous marquent pour toujours.
				</paragraphe>
				<paragraphe>
					Contrairement aux précédentes relations (amicales et familiales), le premier amour fait naître chez nous de nombreuses attentes. Ces dernières sont le plus souvent liées à ce que nous avons vu à la télévision, au cinéma, à ce qu’on nous a raconté, à ce qu’on a vu à la maison… Les expériences amoureuses de nos proches jouent également sur nos attentes. Ainsi, nous faisons des généralités sur le premier amour. Nous voulons décider de comment nous allons aimer, comment nous allons agir dans la relation, ce que nous recherchons dans le couple et ce que nous voulons éviter. Les plus romantiques peuvent même passer des heures à imaginer comment sera leur premier amour.

Mais quand le premier amour frappe, toutes ces attentes s’effondrent. Nous sommes aveuglés par les émotions et pouvons faire des choses que nous trouvions niaises auparavant. A l’inverse, nous pouvons aussi être déçus par la tournure que prend la relation, ne correspondant pas à nos attentes.

S’adapter à la réalité après le choc suscité par la déception peut être une étape difficile. Mais il faut en tirer des enseignements pour les relations à venir. Même si le premier mauvais réflexe est de comparer nos autres conjoints au premier amour.
				</paragraphe>
			</chapitre>
			<chapitre>
				<titre>Le premier amour</titre>
				<paragraphe>
					Le premier amour n’est pas vraiment le premier
La façon dont nous créons des liens avec une autre personne pour la première fois est forcément liée à nos relations antérieures avec nos proches et notre famille. Depuis tout petit, nous établissons des liens plus ou moins intimes avec d’autres personnes. Nous apprenons à partager, à mener, à collaborer, à jouer, à aimer mais aussi à gérer nos premières déceptions.

Les relations que nous avons créées avec nos parents et nos proches en général influent aussi sur notre façon de tisser des liens avec de nouvelles personnes. Nous sommes plus ou moins dépendants, sûrs de nous-mêmes, méfiants, agressifs… Ces relations débutées depuis l’enfance vont nous forger pour le futur.

Voilà pourquoi on peut dire qu’il y a d’autres "amours" avant le premier amour. Ces amours et amitiés, bien qu’elles ne soient pas charnelles, nous apprennent et nous marquent pour toujours.
				</paragraphe>
				<paragraphe>
					Contrairement aux précédentes relations (amicales et familiales), le premier amour fait naître chez nous de nombreuses attentes. Ces dernières sont le plus souvent liées à ce que nous avons vu à la télévision, au cinéma, à ce qu’on nous a raconté, à ce qu’on a vu à la maison… Les expériences amoureuses de nos proches jouent également sur nos attentes. Ainsi, nous faisons des généralités sur le premier amour. Nous voulons décider de comment nous allons aimer, comment nous allons agir dans la relation, ce que nous recherchons dans le couple et ce que nous voulons éviter. Les plus romantiques peuvent même passer des heures à imaginer comment sera leur premier amour.

Mais quand le premier amour frappe, toutes ces attentes s’effondrent. Nous sommes aveuglés par les émotions et pouvons faire des choses que nous trouvions niaises auparavant. A l’inverse, nous pouvons aussi être déçus par la tournure que prend la relation, ne correspondant pas à nos attentes.

S’adapter à la réalité après le choc suscité par la déception peut être une étape difficile. Mais il faut en tirer des enseignements pour les relations à venir. Même si le premier mauvais réflexe est de comparer nos autres conjoints au premier amour.
				</paragraphe>
			</chapitre>
		</section>
	</livre>
		<livre>
		<titre>Amour impossible</titre>
		<annee_prod>2020</annee_prod>
		<isbn>00A003</isbn>
		<auteur>
			<nom>Ahmed mahmoud</nom>
